# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './UI/MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.12.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
	def setupUi(self, MainWindow):
		MainWindow.setObjectName("MainWindow")
		MainWindow.resize(994, 600)
		icon = QtGui.QIcon()
		icon.addPixmap(QtGui.QPixmap(":/icons/icons/246x0w.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
		MainWindow.setWindowIcon(icon)
		self.centralwidget = QtWidgets.QWidget(MainWindow)
		self.centralwidget.setObjectName("centralwidget")
		self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
		self.tableWidget.setGeometry(QtCore.QRect(25, 51, 951, 261))
		self.tableWidget.setObjectName("tableWidget")
		self.tableWidget.setColumnCount(10)
		self.tableWidget.setRowCount(0)
		item = QtWidgets.QTableWidgetItem()
		self.tableWidget.setHorizontalHeaderItem(0, item)
		item = QtWidgets.QTableWidgetItem()
		self.tableWidget.setHorizontalHeaderItem(1, item)
		item = QtWidgets.QTableWidgetItem()
		self.tableWidget.setHorizontalHeaderItem(2, item)
		item = QtWidgets.QTableWidgetItem()
		self.tableWidget.setHorizontalHeaderItem(3, item)
		item = QtWidgets.QTableWidgetItem()
		self.tableWidget.setHorizontalHeaderItem(4, item)
		item = QtWidgets.QTableWidgetItem()
		self.tableWidget.setHorizontalHeaderItem(5, item)
		item = QtWidgets.QTableWidgetItem()
		self.tableWidget.setHorizontalHeaderItem(6, item)
		item = QtWidgets.QTableWidgetItem()
		self.tableWidget.setHorizontalHeaderItem(7, item)
		item = QtWidgets.QTableWidgetItem()
		self.tableWidget.setHorizontalHeaderItem(8, item)
		item = QtWidgets.QTableWidgetItem()
		self.tableWidget.setHorizontalHeaderItem(9, item)
		self.tableWidget.horizontalHeader().setCascadingSectionResizes(False)
		self.tableWidget.horizontalHeader().setDefaultSectionSize(165)
		self.tableWidget.horizontalHeader().setHighlightSections(True)
		self.tableWidget.horizontalHeader().setMinimumSectionSize(52)
		self.tableWidget.horizontalHeader().setStretchLastSection(True)
		self.tableWidget.verticalHeader().setDefaultSectionSize(32)
		self.tableWidget.verticalHeader().setStretchLastSection(False)
		self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
		self.layoutWidget.setGeometry(QtCore.QRect(40, 10, 164, 38))
		self.layoutWidget.setObjectName("layoutWidget")
		self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
		self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
		self.horizontalLayout.setObjectName("horizontalLayout")
		self.newCall = QtWidgets.QPushButton(self.layoutWidget)
		self.newCall.setText("")
		icon1 = QtGui.QIcon()
		icon1.addPixmap(QtGui.QPixmap(":/icons/icons/iconfinder_General_Office_03_3592873.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
		self.newCall.setIcon(icon1)
		self.newCall.setObjectName("newCall")
		self.horizontalLayout.addWidget(self.newCall)
		self.editCall = QtWidgets.QPushButton(self.layoutWidget)
		self.editCall.setText("")
		icon2 = QtGui.QIcon()
		icon2.addPixmap(QtGui.QPixmap(":/icons/icons/iconfinder_General_Office_10_3592815.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
		self.editCall.setIcon(icon2)
		self.editCall.setObjectName("editCall")
		self.horizontalLayout.addWidget(self.editCall)
		self.removeCall = QtWidgets.QPushButton(self.layoutWidget)
		self.removeCall.setText("")
		icon3 = QtGui.QIcon()
		icon3.addPixmap(QtGui.QPixmap(":/icons/icons/iconfinder_General_Office_24_3592821.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
		self.removeCall.setIcon(icon3)
		self.removeCall.setObjectName("removeCall")
		self.horizontalLayout.addWidget(self.removeCall)
		MainWindow.setCentralWidget(self.centralwidget)
		self.menubar = QtWidgets.QMenuBar(MainWindow)
		self.menubar.setGeometry(QtCore.QRect(0, 0, 994, 30))
		self.menubar.setObjectName("menubar")
		MainWindow.setMenuBar(self.menubar)
		self.statusbar = QtWidgets.QStatusBar(MainWindow)
		self.statusbar.setObjectName("statusbar")
		MainWindow.setStatusBar(self.statusbar)

		self.retranslateUi(MainWindow)
		QtCore.QMetaObject.connectSlotsByName(MainWindow)

	def retranslateUi(self, MainWindow):
		_translate = QtCore.QCoreApplication.translate
		MainWindow.setWindowTitle(_translate("MainWindow", "Sistema Premium"))
		item = self.tableWidget.horizontalHeaderItem(0)
		item.setText(_translate("MainWindow", "#"))
		item = self.tableWidget.horizontalHeaderItem(1)
		item.setText(_translate("MainWindow", "Técnica"))
		item = self.tableWidget.horizontalHeaderItem(2)
		item.setText(_translate("MainWindow", "Data"))
		item = self.tableWidget.horizontalHeaderItem(3)
		item.setText(_translate("MainWindow", "Nome Usuário"))
		item = self.tableWidget.horizontalHeaderItem(4)
		item.setText(_translate("MainWindow", "Cartão UFRGS/RG/CPF"))
		item = self.tableWidget.horizontalHeaderItem(5)
		item.setText(_translate("MainWindow", "Laboratório/Outro"))
		item = self.tableWidget.horizontalHeaderItem(6)
		item.setText(_translate("MainWindow", "Equipamento"))
		item = self.tableWidget.horizontalHeaderItem(7)
		item.setText(_translate("MainWindow", "Atividade"))
		item = self.tableWidget.horizontalHeaderItem(8)
		item.setText(_translate("MainWindow", "Tipo de Usuário"))
		item = self.tableWidget.horizontalHeaderItem(9)
		item.setText(_translate("MainWindow", "Origem do Usuário"))


from View import resources_rc
